baseURL: https://ubctcf.com
languageCode: en-ca
title: UBC Technical Career Fair
googleAnalytics: UA-88004303-2

params:
  # Day of the event. Also determines year, i.e. TCF20.
  date: 2020-01-30 10:00:00
  end: 2020-01-31 16:00:00
  location:
    name: UBC AMS Student Nest
    address:
      streetAddress: 6133 University Blvd.
      addressLocality: Vancouver
      postalCode: V6T 1Z1
      addressRegion: BC
      addressCountry: CA

publishdir: docs

tags:
  - premium

menu:
  main:
  - identifier: home
    pre: /img/icons/home.svg
    url: /
    weight: -100
  - identifier: map
    pre: /img/icons/map-marked-alt.svg
    url: /comingsoon/
    weight: -90
  - identifier: companies
    pre: /img/icons/users.svg
    url: /comingsoon/
    weight: -80
  - identifier: help
    pre: /img/icons/question-circle.svg
    url: /help/
    weight: 100
  - identifier: facebook
    pre: /img/icons/facebook.svg
    # Link to the event's facebook page
    url: https://www.facebook.com/events/1413043352198663/
    weight: 110
  - identifier: careersonline
    pre: /img/icons/careers.svg
    url: https://ubc-csm.symplicity.com/students/event/careerfairs/e21600eef949ee3ef4109f5fb47debca/overview?student
    weight: 120
  - identifier: privacy
    pre: /img/icons/file-alt.svg
    url: /privacy/
    weight: 130
