baseURL: https://ubctcf.com
languageCode: en-ca
title: UBC Technical Career Fair
googleAnalytics: UA-88004303-2

params:
  # Day of the event. Also determines year, i.e. TCF20.
  date: 2019-01-31
  # Link to the event's facebook page
  facebook: https://www.facebook.com/events/2121618437859803/

publishdir: docs
